### ISSUE TITLE
Hazard HAS_UNTRACKABLE_DEPENDENCIES

### ISSUE THREAD

**Issue by bheemvennapureddy** [stripe/pg-schema-diff#158] opened 2024-08-26 18:43 UTC
does seq needs to always have a owner ?

```
➜  WebAnalytics git:(Add_postgres_db_migrations) ✗ pg-schema-diff apply --dsn "postgresql://postgres:mysecretpassword@localhost:5432/webanalytics" --schema-dir WebAnalytics.Database.Postgres/db/Scripts/Create
################################## Review plan ##################################
001. CREATE SCHEMA "dbo";
	-- Statement Timeout: 3s

002. CREATE EXTENSION "uuid-ossp" WITH SCHEMA "dbo" VERSION "1.1";
	-- Statement Timeout: 3s

003. CREATE SEQUENCE "dbo"."CspReport_CSP_REPORT_KEY_seq"
	AS bigint
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

004. CREATE SEQUENCE "dbo"."Device_DEVICE_KEY_seq"
	AS integer
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

005. CREATE SEQUENCE "dbo"."LastFocusedField_ID_seq"
	AS bigint
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

006. CREATE SEQUENCE "dbo"."MarketingChannel_MARKETING_CHANNEL_KEY_seq"
	AS integer
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

007. CREATE SEQUENCE "dbo"."MarketingConsentHistory_ID_seq"
	AS integer
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

```

**Comment by bheemvennapureddy** [comment] 2024-08-26 21:15
here is the table for ref : 

```
-- Table: dbo.CSPREPORT

CREATE TABLE IF NOT EXISTS dbo."CspReport"
(
    "CSP_REPORT_KEY" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    "ROUTE_POLICY_KEY" BIGINT,
    "DOCUMENT_URI" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "REFERRER" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "BLOCKED_URI" TEXT COLLATE pg_catalog."default",
    "VIOLATED_DIRECTIVE" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "ORIGINAL_POLICY" TEXT COLLATE pg_catalog."default",
    "EFFECTIVE_DIRECTIVE" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "DISPOSITION" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "LINE_NUMBER" CHARACTER VARYING(20) COLLATE pg_catalog."default",
    "COLUMN_NUMBER" CHARACTER VARYING(20) COLLATE pg_catalog."default",
    "SOURCE_FILE" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "STATUS_CODE" CHARACTER VARYING(100) COLLATE pg_catalog."default",
    "SCRIPT_SAMPLE" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "REQUEST" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "REQUEST_HEADERS" CHARACTER VARYING(255) COLLATE pg_catalog."default",
    "RAW_PAYLOAD" TEXT COLLATE pg_catalog."default",
    "DATE_ENTERED_UTC" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT cspreport_pkey PRIMARY KEY ("CSP_REPORT_KEY")
);
```

**Comment by Navbryce** [comment] 2024-08-26 22:21
If a sequence does not have an owner, then we cannot track who uses it, so we cannot properly order the SQL statement. This also aligns with the behavior of Postgres, which also doesn't try to parse functions for example.

**Comment by bheemvennapureddy** [comment] 2024-08-27 01:31
But isn't that identity is auto generated by Postgres ? We are not using any custom sequence here

**Comment by bheemvennapureddy** [comment] 2024-08-27 14:37
> But isn't that identity is auto generated by Postgres ? We are not using any custom sequence here. I agree that custom sequences needs to be owned by a owner

@Navbryce does that makes sense ?

**Comment by Navbryce** [comment] 2024-08-27 16:31
I can look into this. This particular syntax I'm not familiar with, so I don't know off hand. Notsblu, {size}serial does.

**Comment by bheemvennapureddy** [comment] 2024-08-31 03:02
Related to https://github.com/stripe/pg-schema-diff/issues/163

**Comment by bplunkett-stripe** [comment] 2024-08-31 08:02
Will close since it's a duplicate of #163

**Closed by bplunkett-stripe** 2024-08-31 08:02 UTC

**Comment by bheemvennapureddy** [comment] 2024-11-01 12:17
@bplunkett-stripe @Navbryce i started seeing these again what am i missing here 

```
029. CREATE SEQUENCE "dbo"."rule_rule_key_seq"
	AS bigint
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

030. CREATE SEQUENCE "dbo"."template_template_key_seq"
	AS bigint
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

031. CREATE SEQUENCE "dbo"."templatetype_template_type_key_seq"
	AS bigint
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

032. CREATE SEQUENCE "dbo"."tempmessage_temp_message_key_seq"
	AS bigint
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 CACHE 1 NO CYCLE
;
	-- Statement Timeout: 3s
	-- Hazard HAS_UNTRACKABLE_DEPENDENCIES: This sequence has no owner, so it cannot be tracked. It may be in use by a table or function.

```

Example Schema

```
CREATE TABLE dbo.Rule
(
	RULE_KEY BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	NAME CHARACTER VARYING(255) NOT NULL,
	PARAMETER_NAME CHARACTER VARYING(255),
	TYPE INTEGER NOT NULL,
	DATE_START TIMESTAMPTZ,
	DATE_END TIMESTAMPTZ,
	ENABLED BOOLEAN NOT NULL,
	IS_DELETED BOOLEAN NOT NULL,
	DATE_ENTERED TIMESTAMPTZ NOT NULL,
	DEFINITION CHARACTER VARYING(255),
	WEIGHT INTEGER,
	CONTAINER_KEY INTEGER,
	CONSTRAINT fk_rule_container FOREIGN KEY (CONTAINER_KEY)
		REFERENCES dbo.Container (CONTAINER_KEY) MATCH SIMPLE
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
);

```

**Comment by bheemvennapureddy** [comment] 2024-11-13 18:36
created a new one https://github.com/stripe/pg-schema-diff/issues/180
